# Generated by Django 4.1.3 on 2022-12-01 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('start', models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 1, 6, 7, 42, 219370, tzinfo=datetime.timezone.utc))),
                ('end', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
