# Generated by Django 4.1.3 on 2022-12-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
