# Generated by Django 4.1.3 on 2022-12-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_coupon_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
