# Generated by Django 4.1.3 on 2022-12-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
