# Generated by Django 4.1.3 on 2022-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
