# Generated by Django 4.1.3 on 2022-11-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='cover/')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('status', models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Both', 'Both')], max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.brand')),
                ('category', models.ManyToManyField(related_name='cat_product', to='products.category')),
                ('color', models.ManyToManyField(blank=True, null=True, related_name='color_product', to='products.color')),
                ('size', models.ManyToManyField(blank=True, null=True, related_name='size_products', to='products.size')),
            ],
        ),
    ]
