# Generated by Django 4.1.3 on 2022-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='var_color', to='products.color'),
        ),
    ]
