# Generated by Django 4.1.3 on 2022-11-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_sell_product_total_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var_color', to='products.color'),
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var_size', to='products.size'),
        ),
    ]
