# Generated by Django 4.1.3 on 2022-12-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_color_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
